wallpaper {
    monitor = 
    path = $HOME/.local/state/wallpaper-rotate/current
    fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off

